### ISSUE TITLE
Support combining filter types

### ISSUE THREAD

**Issue by dudeofawesome** [afterxleep/Bouncer#37]
For example, I'd like to block messages from full-length numbers containing a URL. I don't see a way to currently combine those 2 rules so both have to match.

**Comment by afterxleep** [comment]
Unfortunately, there's no way in the UI to do that and no plans to implement it, but you could select the "Any Part of the Message" option and write a Regular expression to match both URL's and phone numbers.

Here are a few examples to play with:  https://uibakery.io/regex-library/url

**Comment by dudeofawesome** [comment]
What does a sample string look like when "Any part of the message" is chosen?

**Comment by afterxleep** [comment]
This quick example should matchany message with four consecutive numbers and a URL starting with HTTP or https

[0-9][0-9][0-9][0-9].* (http|https):

You can test it and generate your own at [Regex101](https://regex101.com)

**Comment by dudeofawesome** [comment]
Could you give an example of a payload that Bouncer will attempt to match the refer against?

**Comment by afterxleep** [comment]
It’s just a concatenation of message sender and content, both
lowercased.


On September 14, 2022, Daniel Bernal ***@***.***> wrote:
> Could you give an example of a payload that Bouncer will attempt to
> match the refer against?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/afterxleep/Bouncer/issues/37#issuecomment-
1247181765>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAI2MPLML2LKPFYXMKSMQXDV6IOCVANCNFSM6AAAAAAQK6WRMQ>.
You are receiving this because you modified the open/close state.Message
ID: ***@***.***>
