### ISSUE TITLE
Block Lists

### ISSUE THREAD

**Issue by captn3m0** [afterxleep/Bouncer#39]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to rely on trusted individuals who can publish block lists in an exportable format.

**Describe the solution you'd like**
A list of URLs somewhere in the application, where I can configure an external blocklist source. This blocklist would include all the relevant parts - category/regex/match. The blocklist could be imported on a scheduled frequency (once a day perhaps), and removing a blocklist would automatically remove all the rules associated with the same.

**Describe alternatives you've considered**
A simple export/import mechanism.

**Additional context**
Such a feature would help in increasing adoption of Bouncer.

**Comment by afterxleep** [comment]
Let's look into #40 first.

**Comment by afterxleep** [comment]
You'll find an option to import and export lists in JSON format in the latest Testflight beta, which allows you to manage custom lists int the app.    Adding third party lists is interesting, but still requires plenty more development because you'll need to manage both. (Yours and third party), and also sync with remote servers, etc.

I'll keep it in my radar for future releases :)

**Comment by afterxleep** [comment]
Join the beta test here: https://testflight.apple.com/join/Lls6XUfx
